# Add your fake files and funny messages here!

fake_files = [
    "C:/Windows/System32/important.dll",
    "C:/Windows/Temp/secret_recipe.txt",
    "C:/Users/User/Documents/secret_plans.txt",
    "C:/Users/User/AppData/Roaming/doom_saver.bat",
    "C:/Program Files/SuspiciousApp/sus.exe",
    "C:/Program Files/Common Files/UnicornDriver.sys",
    "D:/Games/AncientGame/savefile.corrupt",
    "C:/Windows/Fonts/comic_sans_neue.ttf",
    "/usr/bin/ultimate_hack_tool.sh",
    "/usr/local/bin/self_destruct.sh",
    "/etc/passwd",
    "/etc/whywouldyouputthishere.conf",
    "/var/log/cat_pictures.log",
    "/tmp/hidden_gem.tmp",
    "/opt/secret_folder/forbidden_knowledge.pdf",
    "/home/user/DefinitelyNotMalware.py",
    "/home/user/.config/quantum_settings.yaml",
    "/dev/null",
    "/mnt/usb/totallylegit.iso",
    "A:/floppy_disk/nostalgia.exe",
    "Z:/network_drive/aliensighting.jpg",
    "C:/Windows/System32/404notfound.sys",
    "C:/super_secret/never_gonna_give_you_up.mp3",
    "/private/var/root/evilplan.docx",
    "/Users/Shared/README_DO_NOT_DELETE.txt",
    "/Applications/Clippy.app",
    "C:/Windows/WinSxS/backup_of_backup_of_backup.zip"
    # Add new file paths below:
]

funny_messages = [
    "Reticulating splines...",
    "Counting backwards from infinity...",
    "Calculating the meaning of life...",
    "Unpacking memes...",
    "Reversing the polarity of the neutron flow...",
    "Consulting the magic 8-ball...",
    "Compiling with 100% more sarcasm...",
    "Replacing all your files with cat pictures...",
    "Mining Bitcoin (just kidding)...",
    "Optimizing useless code...",
    "Pretending to be busy...",
    "Downloading RAM...",
    "Please wait, or don’t. I’m just a script.",
    "Upgrading your sense of humor...",
    "Fixing the flux capacitor...",
    "Summoning rubber ducks for debugging...",
    "Debugging the debugger...",
    "Translating binary to emoji...",
    "Herding electrons...",
    "Faking progress bar...",
    "Launching the launch sequence...",
    "Turning it off and on again...",
    "Stealing cookies (not the browser kind)...",
    "Encrypting all vowels...",
    "Reinstalling clippy...",
    "Feeding the hamsters that power your CPU...",
    "Befriending firewalls...",
    "Writing poetry in assembly language...",
    "Searching for lost socks...",
    "Negotiating with procrastination daemons...",
    "Asking the AI overlords for permission...",
    "Unlocking secret achievements...",
    "Redirecting to the mainframe...",
    "Just a flesh wound!",
    "404: Joke not found.",
    "Performing quantum entanglement...",
    "Rebooting the space-time continuum...",
    "Making coffee break mandatory...",
    "Running with scissors (dangerous!)",
    "Blinking rapidly to simulate activity...",
    "Tuning the banjo for the next step...",
    "Pretending to care...",
    "Making up more funny messages...",
    "Simulating a blue screen of happiness..."
    # Add new messages below:
]